# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Benvin D
#
# This file is part of PrepVault, released under the GNU Affero General
# Public License v3.0 or later. See the LICENSE file for details.
"""baseline schema

Revision ID: 0c2318d5b440
Revises: 
Create Date: 2026-06-22 21:13:49.960275
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2318d5b440'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('judge', sa.String(length=40), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'judge', 'day', name='uq_user_judge_day')
    )
    with op.batch_alter_table('activity_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_days_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_days_user_id'), ['user_id'], unique=False)

    op.create_table('judge_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('judge', sa.String(length=40), nullable=False),
    sa.Column('session_cookie', sa.Text(), nullable=True),
    sa.Column('csrftoken', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'judge', name='uq_user_judge_cred')
    )
    with op.batch_alter_table('judge_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judge_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('judge', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('topics', sa.String(length=500), nullable=True),
    sa.Column('languages', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('date_solved', sa.Date(), nullable=True),
    sa.Column('first_solved_at', sa.DateTime(), nullable=True),
    sa.Column('last_revised', sa.Date(), nullable=True),
    sa.Column('next_revision', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('revisit', sa.Boolean(), nullable=False),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('submissions_fetched', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'judge', 'slug', name='uq_user_judge_slug')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_problems_user_id'), ['user_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=40), nullable=False),
    sa.Column('lang', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('runtime', sa.String(length=40), nullable=True),
    sa.Column('memory', sa.String(length=40), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'external_id', name='uq_problem_submission')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_problem_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_user_id'))
        batch_op.drop_index(batch_op.f('ix_problems_slug'))

    op.drop_table('problems')
    with op.batch_alter_table('judge_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judge_credentials_user_id'))

    op.drop_table('judge_credentials')
    with op.batch_alter_table('activity_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_days_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_days_day'))

    op.drop_table('activity_days')
    op.drop_table('users')
    # ### end Alembic commands ###
